<a href="https://colab.research.google.com/github/pratikiiitb2013/END2_p1/blob/main/Session3/%20END2_S3_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim 
from torchvision.transforms import transforms
from torch.utils.data import DataLoader
from torch.utils.data import Dataset
from random import randint

In [3]:
# class ExampleDataset(Dataset):
#     def __init__(self, data):
#         self.data = data
#     def __len__(self):
#         return len(self.data)
    
#     def __getitem__(self, idx):
#         return self.data[idx]

In [4]:
def get_device():
    if torch.cuda.is_available():
        device = 'cuda:0'
    else:
        device = 'cpu'
    return device
device = get_device()
print(device)

cpu


In [5]:
# sample_data = np.arange(0, 10)
# print('The whole data: ', sample_data)
# dataset = ExampleDataset(sample_data)
# print('Number of samples in the data: ', len(dataset))
# print(dataset[2])
# print(dataset[0:5])

In [6]:
!wget https://pjreddie.com/media/files/mnist_train.csv

--2021-05-18 05:29:07--  https://pjreddie.com/media/files/mnist_train.csv
Resolving pjreddie.com (pjreddie.com)... 128.208.4.108
Connecting to pjreddie.com (pjreddie.com)|128.208.4.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 109575994 (104M) [application/octet-stream]
Saving to: ‘mnist_train.csv’

mnist_train.csv     100%[===================>] 104.50M  38.1MB/s    in 2.7s    

2021-05-18 05:29:11 (38.1 MB/s) - ‘mnist_train.csv’ saved [109575994/109575994]



In [7]:
!ls

mnist_train.csv  sample_data


In [8]:
df_train = pd.read_csv('mnist_train.csv', header=None)

# get the image pixel values and labels
# train_labels = df_train.iloc[:, 0]
# train_images = df_train.iloc[:, 1:]
# test_labels = df_test.iloc[:, 0]
# test_images = df_test.iloc[:, 1:]

In [113]:
# custom dataset
class customMNISTDataset(Dataset):

  def __init__(self, data, transforms=None):
    self.X = data.iloc[:, 1:]
    self.y = data.iloc[:, 0]
    self.transforms = transforms

  def __len__(self):
    return len(self.X)

  def __getitem__(self, idx):
    img_data = self.X.iloc[idx, :]
    # if isinstance(idx, slice):
    #     img_data = np.array([i.reshape(1,28, 28) for i in np.array(img_data)])
    #     rand_no = np.array([randint(0, 9) for i in np.array(img_data)])
    #     y1 = np.array(self.y[idx])
    #     y2 = y1 + rand_no
    # else:
    img_data = np.array(img_data).astype(np.uint8).reshape(28, 28, 1)
    rand_no = randint(0, 9)
    y1 = self.y[idx]
    y2 = y1 + rand_no
    
    if self.transforms:
      img_data = self.transforms(img_data)
    return img_data, rand_no, y1, y2


transform=transforms.Compose([
    transforms.ToTensor()
])

train_ds = customMNISTDataset(df_train, transform)
print('Number of samples in the data: ', len(dataset))

trainloader = DataLoader(train_ds, batch_size=10, shuffle=True)
aa = next(iter(trainloader))
aa
# aa[1].type()
# print(dataset[2])
# print(dataset[0:5])

# batch = next(iter(trainloader))

# len(batch), type(batch)

Number of samples in the data:  60000


[tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]]],
 
 
         [[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]]],
 
 
         [[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]]],
 
 
         ...,
 
 
         [[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ..

In [171]:
import torch.nn.functional as F

def conv_block(input_size, output_size, kernel_size):
    block = nn.Sequential(
        nn.Conv2d(in_channels=input_size, out_channels=output_size, kernel_size=kernel_size), nn.ReLU(), nn.MaxPool2d((2, 2)),
    )
    return block

class Network(nn.Module):
  def __init__(self):
        super().__init__()
        self.conv1 = conv_block(input_size=1, output_size=6, kernel_size=3)
        self.conv2 = conv_block(input_size=6, output_size=12, kernel_size=3)

        self.relu = nn.ReLU()
        self.fc1 = nn.Linear(in_features=12*5*5, out_features=16)
        self.fc2 = nn.Linear(in_features=16, out_features=5)

        self.fc3 = nn.Linear(in_features=10, out_features=10)
        self.fc4 = nn.Linear(in_features=10, out_features=5)

        self.fc5 = nn.Linear(in_features=10, out_features=50)
        self.fc6 = nn.Linear(in_features=50, out_features=29)






  def forward(self, img, ohe):
    img = self.conv1(img)
    print(img.shape)
    img = self.conv2(img)
    print(img.shape)
    img = img.reshape(img.shape[0], -1)  # img = img.reshape(-1, 12*5*5)
    print(img.shape)
    img = self.relu(self.fc1(img))
    print(img.shape)
    img = self.relu(self.fc2(img))
    print(img.shape)
    print(ohe.shape)
    ohe = self.relu(self.fc3(ohe))
    print(ohe.shape)
    ohe = self.relu(self.fc4(ohe))
    print(ohe.shape)
    x = torch.cat((img, ohe), dim=1)
    print(x.shape)
    x = self.relu(x)
    x = self.relu(self.fc5(x))
    print(x.shape)
    x = self.fc6(x)
    print(x.shape)
    return x, F.softmax(x[:,0:10], dim=1),F.softmax(x[:,10:], dim=1)
    




In [172]:
sample = next(iter(train_ds)) 
image, randno, label, sm = sample

image.shape, image.unsqueeze(0).shape, randno, label, sm
# sample

(torch.Size([1, 28, 28]), torch.Size([1, 1, 28, 28]), 0, 5, 5)

In [173]:
F.one_hot(torch.tensor(randno), num_classes=10)
torch.tensor(randno).unsqueeze(0)

one_hot = torch.nn.functional.one_hot(torch.tensor(randno).to(torch.int64), 10).float()
one_hot.type()

'torch.FloatTensor'

In [174]:
network = Network()
# F.one_hot(x, num_classes=6)
pred1,p2,p3 = network(image.unsqueeze(0), F.one_hot(torch.tensor(randno).unsqueeze(0), num_classes=10).float())
pred1,p2,p3

torch.Size([1, 6, 13, 13])
torch.Size([1, 12, 5, 5])
torch.Size([1, 300])
torch.Size([1, 16])
torch.Size([1, 5])
torch.Size([1, 10])
torch.Size([1, 10])
torch.Size([1, 5])
torch.Size([1, 10])
torch.Size([1, 50])
torch.Size([1, 29])


(tensor([[-0.1078,  0.1815,  0.2673,  0.0864,  0.1702,  0.1525, -0.1392,  0.0451,
          -0.0085,  0.0209, -0.0851, -0.1327,  0.1246,  0.1310, -0.0107,  0.0360,
          -0.0293, -0.0563, -0.1314, -0.1120, -0.0450,  0.0460,  0.2328, -0.0055,
          -0.0919, -0.2226,  0.1009, -0.0043, -0.0850]],
        grad_fn=<AddmmBackward>),
 tensor([[0.0833, 0.1113, 0.1213, 0.1012, 0.1101, 0.1081, 0.0808, 0.0971, 0.0920,
          0.0948]], grad_fn=<SoftmaxBackward>),
 tensor([[0.0489, 0.0466, 0.0603, 0.0607, 0.0527, 0.0552, 0.0517, 0.0504, 0.0467,
          0.0476, 0.0509, 0.0558, 0.0672, 0.0530, 0.0486, 0.0426, 0.0589, 0.0530,
          0.0489]], grad_fn=<SoftmaxBackward>))

In [176]:
data_loader = torch.utils.data.DataLoader(
    train_ds, 
    batch_size=10
)

batch = next(iter(data_loader))
len(batch)
batch

images, randnos, labels, sms = batch

pred1,p2,p3 = network(images, F.one_hot(torch.tensor(randnos), num_classes=10).float())
pred1.shape,p2.shape,p3.shape
pred1,p2,p3

torch.Size([10, 6, 13, 13])
torch.Size([10, 12, 5, 5])
torch.Size([10, 300])
torch.Size([10, 16])
torch.Size([10, 5])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 5])
torch.Size([10, 10])
torch.Size([10, 50])
torch.Size([10, 29])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if sys.path[0] == '':


(tensor([[-1.0784e-01,  1.8153e-01,  2.6730e-01,  8.6431e-02,  1.7023e-01,
           1.5254e-01, -1.3921e-01,  4.5118e-02, -8.4856e-03,  2.0949e-02,
          -8.5051e-02, -1.3275e-01,  1.2456e-01,  1.3097e-01, -1.0723e-02,
           3.5996e-02, -2.9267e-02, -5.6310e-02, -1.3139e-01, -1.1200e-01,
          -4.5019e-02,  4.6014e-02,  2.3278e-01, -5.4749e-03, -9.1875e-02,
          -2.2261e-01,  1.0095e-01, -4.2879e-03, -8.4960e-02],
         [-1.1621e-01,  1.7115e-01,  2.5696e-01,  8.3134e-02,  1.6481e-01,
           1.4741e-01, -1.3734e-01,  4.4779e-02, -2.0175e-03,  1.8433e-02,
          -7.2665e-02, -1.2769e-01,  1.1981e-01,  1.2560e-01, -1.5784e-02,
           1.3237e-02, -3.2371e-02, -6.5831e-02, -1.2765e-01, -1.1603e-01,
          -3.9650e-02,  4.7715e-02,  2.2941e-01, -3.9303e-03, -9.6931e-02,
          -2.1857e-01,  1.0627e-01, -7.3640e-03, -7.6801e-02],
         [-1.0775e-01,  1.8017e-01,  2.6466e-01,  8.1137e-02,  1.6996e-01,
           1.4791e-01, -1.4124e-01,  4.5881e-02, 